### ISSUE TITLE
实现login，register，logout，current，change-password五个接口，建议加入cookie

### ISSUE THREAD

**Issue by xinyizhiren** [eat-what-in-noon/blog#3]
加入cookie可参考以下代码

    @PostMapping("/login")
    public boolean doLogin(@RequestBody User user, HttpServletResponse response) {
        if (userMapper.doLogins(user.getUser_name(), user.getPassword())) {
            // 创建并设置 Cookie
            Cookie cookie = new Cookie("name", user.getUser_name());
            cookie.setMaxAge(7 * 24 * 60 * 60); // 7 days
            cookie.setPath("/");
            response.addCookie(cookie);

            // 将用户信息存储在 Redis 中
            redisTemplate.opsForValue().set("user:" + user.getUser_name(), userMapper.findByUsername(user.getUser_name()));

            return true;
        } else {
            return false;
        }
    }

    @PostMapping("/register")
    public ResponseEntity<String> doRegister(@RequestBody User user) {
        if (user != null && userMapper.insert(user) > 0) {
            // 将用户信息存储在 Redis 中
            redisTemplate.opsForValue().set("user:" + user.getUser_name(), user);
            return ResponseEntity.ok("注册成功");
        }
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("注册失败");
    }

    @GetMapping("/logout")
    public ResponseEntity<String> logout(HttpServletRequest request, HttpServletResponse response) {
        // 获取用户 Cookie
        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                if (cookie.getName().equals("name")) {
                    String username = cookie.getValue();

                    // 删除 Redis 中的用户信息
                    redisTemplate.delete("user:" + username);

                    // 删除用户 Cookie
                    cookie.setMaxAge(0);
                    cookie.setPath("/");
                    response.addCookie(cookie);

                    return ResponseEntity.ok("注销成功");
                }
            }
        }
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("未找到用户 Cookie");
    }

    @GetMapping("/current")
    public ResponseEntity<Object> getCurrentUser(HttpServletRequest request) {
        // 获取用户 Cookie
        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                if (cookie.getName().equals("name")) {
                    String username = cookie.getValue();

                    // 从 Redis 中获取用户信息
                    Object user = redisTemplate.opsForValue().get("user:" + username);
                    if (user != null) {
                        return ResponseEntity.ok(user);
                    } else {
                        return ResponseEntity.status(HttpStatus.NOT_FOUND).body("用户信息未找到");
                    }
                }
            }
        }
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("未找到用户 Cookie");
    }

**Comment by Bad-maker** [comment]
已完成任务并push
